### ISSUE TITLE
Sprockets error: undefined method `register_preprocessor' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by psugihara** [jsdf/sprockets-coffee-react#10]
```
$~ rake assets:precompile
I, [2015-12-20T17:27:53.970112 #10473]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
/Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/sprockets-coffee-react-3.4.0/lib/sprockets/coffee-react/engine.rb:22:in `block in <class:Engine>': undefined method `register_preprocessor' for nil:NilClass (NoMethodError)
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/petersugihara/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/petersugihara/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/petersugihara/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/petersugihara/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/petersugihara/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/petersugihara/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/petersugihara/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/petersugihara/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/petersugihara/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /Users/petersugihara/open_listings/config/environment.rb:19:in `<top (required)>'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/spring-1.5.0/lib/spring/application.rb:92:in `preload'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/spring-1.5.0/lib/spring/application.rb:143:in `serve'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/spring-1.5.0/lib/spring/application.rb:131:in `block in run'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/spring-1.5.0/lib/spring/application.rb:125:in `loop'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/spring-1.5.0/lib/spring/application.rb:125:in `run'
	from /Users/petersugihara/.rvm/gems/ruby-2.2.0@OpenListings/gems/spring-1.5.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/petersugihara/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/petersugihara/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

Same output when I run `rails s`.

Any ideas? I think it might have something to do with a sprockets upgrade. Are other people running this with the latest rails version?

Thanks!
Peter

**Comment by jsdf** [comment]
What version of sprockets are you using?

**Comment by psugihara** [comment]
3.5.2

```
GIT
  remote: git://github.com/openlistings/rets.git
  revision: 816f022f1c2f1447c266a2e8f748727fc483d21e
  ref: 816f022f1c2f1447c266a2e8f748727fc483d21e
  branch: client_requires_logout
  specs:
    rets (0.9.0.20150611164600)
      http-cookie (~> 1.0.0)
      httpclient (~> 2.6.0)
      nokogiri (~> 1.5)

GEM
  remote: https://rubygems.org/
  specs:
    RubyInline (3.12.4)
      ZenTest (~> 4.3)
    ZenTest (4.11.0)
    aasm (4.0.8)
    actionmailer (4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.5)
      actionview (= 4.2.5)
      activesupport (= 4.2.5)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionpack-page_caching (1.0.2)
      actionpack (>= 4.0.0, < 5)
    actionview (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    active_model_serializers (0.9.3)
      activemodel (>= 3.2)
    activejob (4.2.5)
      activesupport (= 4.2.5)
      globalid (>= 0.3.0)
    activemodel (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
    activerecord (4.2.5)
      activemodel (= 4.2.5)
      activesupport (= 4.2.5)
      arel (~> 6.0)
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    analytics-ruby (2.0.13)
    analytics-ruby-mock (0.0.7)
    arel (6.0.3)
    ast (2.2.0)
    astrolabe (1.3.1)
      parser (~> 2.2)
    autoprefixer-rails (6.2.0)
      execjs
      json
    awesome_print (1.6.1)
    aws-sdk (2.2.5)
      aws-sdk-resources (= 2.2.5)
    aws-sdk-core (2.2.5)
      jmespath (~> 1.0)
    aws-sdk-resources (2.2.5)
      aws-sdk-core (= 2.2.5)
    aws-sdk-v1 (1.66.0)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.6)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    bower-rails (0.10.0)
    bson (4.0.0)
    buftok (0.2.0)
    builder (3.2.2)
    capistrano (3.4.0)
      i18n
      rake (>= 10.0.0)
      sshkit (~> 1.3)
    capistrano-bower (1.1.0)
      capistrano (~> 3.0)
    capistrano-bundler (1.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-passenger (0.2.0)
      capistrano (~> 3.0)
    capistrano-rails (1.1.5)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-screenshot (1.0.11)
      capybara (>= 1.0, < 3)
      launchy
    celluloid (0.17.2)
      celluloid-essentials
      celluloid-extras
      celluloid-fsm
      celluloid-pool
      celluloid-supervision
      timers (>= 4.1.1)
    celluloid-essentials (0.20.5)
      timers (>= 4.1.1)
    celluloid-extras (0.20.5)
      timers (>= 4.1.1)
    celluloid-fsm (0.20.5)
      timers (>= 4.1.1)
    celluloid-pool (0.20.5)
      timers (>= 4.1.1)
    celluloid-supervision (0.20.5)
      timers (>= 4.1.1)
    childprocess (0.5.8)
      ffi (~> 1.0, >= 1.0.11)
    chronic (0.10.2)
    cliver (0.3.2)
    coderay (1.1.0)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-rails-source-maps (1.4.0)
      coffee-script-source (>= 1.6.1)
    coffee-react (3.4.0)
      execjs
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    coffeelint (1.14.0)
      coffee-script
      execjs
      json
    commander (4.3.5)
      highline (~> 1.7.2)
    concurrent-ruby (1.0.0)
    connection_pool (2.2.0)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    curb (0.8.8)
    daemons (1.2.3)
    dalli (2.7.4)
    database_cleaner (1.5.1)
    dbf (3.0.3)
    debug_inspector (0.0.2)
    did_you_mean (0.9.10)
      interception
    docile (1.1.5)
    domain_name (0.5.25)
      unf (>= 0.0.5, < 1.0.0)
    eco (1.0.0)
      coffee-script
      eco-source
      execjs
    eco-source (1.1.0.rc.1)
    equalizer (0.0.10)
    erubis (2.7.0)
    eventmachine (1.0.8)
    exception_notification (4.1.2)
      actionmailer (~> 4.0)
      activesupport (~> 4.0)
    exception_notification-rake (0.2.1)
      exception_notification (~> 4.1.0)
      rake (>= 0.9.0)
    execjs (2.6.0)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    faraday_middleware (0.10.0)
      faraday (>= 0.7.4, < 0.10)
    ffi (1.9.10)
    font-awesome-rails (4.5.0.0)
      railties (>= 3.2, < 5.0)
    font-awesome-sass (4.4.0)
      sass (>= 3.2)
    fullcontact (0.12.0)
      faraday (~> 0.9.0)
      faraday_middleware (>= 0.9)
      hashie (>= 2.0, < 4.0)
      plissken
    fuzzy-string-match (0.9.7)
      RubyInline (>= 3.8.6)
    gem-shut-the-fuck-up (1.0.0)
    gibbon (2.2.0)
      faraday (>= 0.9.1)
      multi_json (>= 1.11.0)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    gmail (0.6.0)
      gmail_xoauth (>= 0.3.0)
      mail (>= 2.2.1)
    gmail_xoauth (0.4.1)
      oauth (>= 0.3.6)
    haml (4.0.7)
      tilt
    hash_diff (0.8.0)
    hashdiff (0.2.3)
    hashids (1.0.2)
    hashie (3.4.3)
    highline (1.7.8)
    hipchat (1.5.2)
      httparty
      mimemagic
    hiredis (0.6.0)
    hitimes (1.2.3)
    houston (2.2.3)
      commander (~> 4.1)
      json
    http (0.9.8)
      addressable (~> 2.3)
      http-cookie (~> 1.0)
      http-form_data (~> 1.0.1)
      http_parser.rb (~> 0.6.0)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    http-form_data (1.0.1)
    http_parser.rb (0.6.0)
    httparty (0.13.7)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    httpclient (2.6.0.1)
    i18n (0.7.0)
    interception (0.5)
    jmespath (1.1.3)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    koala (2.2.0)
      addressable
      faraday
      multi_json
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.4.1)
      launchy (~> 2.2)
    libv8 (4.5.95.5)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mandriller (0.2.0)
      actionmailer (>= 3.0)
      multi_json
    memoizable (0.4.2)
      thread_safe (~> 0.3, >= 0.3.1)
    metaclass (0.0.4)
    method_source (0.8.2)
    mime-types (2.99)
    mimemagic (0.3.0)
    mini_magick (4.3.6)
    mini_portile2 (2.0.0)
    minitest (5.8.2)
    minitest-retry (0.1.4)
      minitest (>= 5.0)
    minitest-stub_any_instance (1.0.1)
    mocha (1.1.0)
      metaclass (~> 0.0.1)
    mongo (2.2.1)
      bson (~> 4.0)
    mongoid (5.0.1)
      activemodel (~> 4.0)
      mongo (~> 2.1)
      origin (~> 2.1)
      tzinfo (>= 0.3.37)
    multi_json (1.11.2)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    naught (1.1.0)
    nested_form (0.3.2)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (3.0.1)
    newrelic_rpm (3.14.0.305)
    nokogiri (1.6.7)
      mini_portile2 (~> 2.0.0.rc2)
    numbers_and_words (0.10.0)
      activesupport
      i18n
    oauth (0.4.7)
    omniauth (1.2.2)
      hashie (>= 1.2, < 4)
      rack (~> 1.0)
    omniauth-oauth (1.1.0)
      oauth
      omniauth (~> 1.0)
    omniauth-twitter (1.2.1)
      json (~> 1.3)
      omniauth-oauth (~> 1.1)
    origin (2.1.1)
    pHash (1.1.5)
      ffi (~> 1.0)
    parser (2.2.3.0)
      ast (>= 1.1, < 3.0)
    pdf-core (0.6.0)
    pdf-forms (0.6.1)
      cliver (~> 0.3.2)
      safe_shell (~> 1.0)
    pdf-toolkit (1.1.0)
    plissken (0.2.0)
      symbolize (~> 4.2)
    poltergeist (1.8.1)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    powerpack (0.1.1)
    prawn (2.0.2)
      pdf-core (~> 0.6.0)
      ttfunk (~> 1.4.0)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.6.4)
    rack-pjax (0.8.0)
      nokogiri (~> 1.5)
      rack (~> 1.1)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.5)
      actionmailer (= 4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      activemodel (= 4.2.5)
      activerecord (= 4.2.5)
      activesupport (= 4.2.5)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.5)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails_admin (0.7.0)
      builder (~> 3.1)
      coffee-rails (~> 4.0)
      font-awesome-rails (>= 3.0, < 5)
      haml (~> 4.0)
      jquery-rails (>= 3.0, < 5)
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.14)
      nested_form (~> 0.3)
      rack-pjax (~> 0.7)
      rails (~> 4.0)
      remotipart (~> 1.0)
      safe_yaml (~> 1.0)
      sass-rails (>= 4.0, < 6)
    railties (4.2.5)
      actionpack (= 4.2.5)
      activesupport (= 4.2.5)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.0.0)
    rake (10.4.2)
    redis (3.2.2)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    redis_rate_limiter (0.0.9)
      redis
    remotipart (1.2.1)
    retryable (2.0.3)
    rgeo (0.4.0)
    rgeo-geojson (0.3.1)
      rgeo (~> 0.3)
    rgeo-shapefile (0.2.3)
      dbf (>= 1.7.0)
      rgeo (>= 0.3.3)
    rubocop (0.32.1)
      astrolabe (~> 1.3)
      parser (>= 2.2.2.5, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.4)
    ruby-progressbar (1.7.5)
    rubyzip (1.1.7)
    safe_shell (1.0.3)
    safe_yaml (1.0.4)
    sass (3.4.20)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    selenium-webdriver (2.47.1)
      childprocess (~> 0.5)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0)
    sidekiq (3.5.3)
      celluloid (~> 0.17.2)
      connection_pool (~> 2.2, >= 2.2.0)
      json (~> 1.0)
      redis (~> 3.2, >= 3.2.1)
      redis-namespace (~> 1.5, >= 1.5.2)
    sidekiq-middleware (0.3.0)
      sidekiq (>= 2.12.4)
    sidekiq-rate-limiter (0.1.0)
      redis
      redis_rate_limiter
      sidekiq (>= 2.0, < 4.0)
    simple_oauth (0.3.1)
    simple_xlsx_reader (1.0.2)
      nokogiri
      rubyzip
    simplecov (0.9.2)
      docile (~> 1.1.0)
      multi_json (~> 1.0)
      simplecov-html (~> 0.9.0)
    simplecov-html (0.9.0)
    sinatra (1.4.6)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    sitemap_generator (5.1.0)
      builder
    slop (3.6.0)
    spliner (1.0.6)
    spring (1.5.0)
    sprockets (3.5.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-coffee-react (3.4.0)
      coffee-react (>= 3.4.0)
      coffee-script
      sprockets
      tilt
    sprockets-rails (3.0.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.8.1)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    symbolize (4.5.2)
      activemodel (>= 3.2, < 5)
      activesupport (>= 3.2, < 5)
      i18n
    thin (1.6.4)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0, >= 1.0.4)
      rack (~> 1.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    timecop (0.8.0)
    timers (4.1.1)
      hitimes
    ttfunk (1.4.0)
    twitter (5.15.0)
      addressable (~> 2.3)
      buftok (~> 0.2.0)
      equalizer (= 0.0.10)
      faraday (~> 0.9.0)
      http (>= 0.4, < 0.10)
      http_parser.rb (~> 0.6.0)
      json (~> 1.8)
      memoizable (~> 0.4.0)
      naught (~> 1.0)
      simple_oauth (~> 0.3.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    tzip (0.0.4)
      activesupport (>= 2.3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    uuidtools (2.1.5)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    webmock (1.22.3)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    websocket (1.2.2)
    websocket-driver (0.6.3)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)
    whenever (0.9.4)
      chronic (>= 0.6.3)
    xpath (2.0.0)
      nokogiri (~> 1.3)
    yui-compressor (0.12.0)

PLATFORMS
  ruby

DEPENDENCIES
  aasm (= 4.0.8)
  actionpack-page_caching (= 1.0.2)
  active_model_serializers (= 0.9.3)
  analytics-ruby (= 2.0.13)
  analytics-ruby-mock (= 0.0.7)
  awesome_print (= 1.6.1)
  aws-sdk (= 2.2.5)
  aws-sdk-v1 (= 1.66.0)
  bcrypt (= 3.1.10)
  bootstrap-sass (= 3.3.6)
  bower-rails (= 0.10.0)
  capistrano (= 3.4.0)
  capistrano-bower (= 1.1.0)
  capistrano-bundler (= 1.1.4)
  capistrano-passenger (= 0.2.0)
  capistrano-rails (= 1.1.5)
  capybara (= 2.5.0)
  capybara-screenshot (= 1.0.11)
  coffee-rails (= 4.1.1)
  coffee-rails-source-maps (= 1.4.0)
  coffee-script-source (= 1.10.0)
  coffeelint (= 1.14.0)
  curb (= 0.8.8)
  dalli (= 2.7.4)
  database_cleaner (= 1.5.1)
  did_you_mean (= 0.9.10)
  eco (= 1.0.0)
  exception_notification (= 4.1.2)
  exception_notification-rake (= 0.2.1)
  factory_girl (= 4.5.0)
  font-awesome-sass (= 4.4.0.0)
  fullcontact (= 0.12.0)
  fuzzy-string-match
  gem-shut-the-fuck-up (= 1.0.0)
  gibbon (= 2.2.0)
  gmail (= 0.6.0)
  hash_diff (= 0.8.0)
  hashids (= 1.0.2)
  hipchat (= 1.5.2)
  hiredis (= 0.6.0)
  houston (= 2.2.3)
  json (= 1.8.3)
  koala (= 2.2.0)
  letter_opener (= 1.4.1)
  libv8 (= 4.5.95.5)
  mandriller (= 0.2.0)
  mini_magick (= 4.3.6)
  minitest (= 5.8.2)
  minitest-retry (= 0.1.4)
  minitest-stub_any_instance (= 1.0.1)
  mocha (= 1.1.0)
  mongoid (= 5.0.1)
  newrelic_rpm (= 3.14.0.305)
  nokogiri (= 1.6.7)
  numbers_and_words (= 0.10.0)
  omniauth (= 1.2.2)
  omniauth-twitter (= 1.2.1)
  pHash (= 1.1.5)
  pdf-forms (= 0.6.1)
  pdf-toolkit (= 1.1.0)
  poltergeist (= 1.8.1)
  prawn (= 2.0.2)
  pry (= 0.10.3)
  quiet_assets (= 1.1.0)
  rails (= 4.2.5)
  rails_admin (= 0.7.0)
  rake (= 10.4.2)
  redis (= 3.2.2)
  retryable (= 2.0.3)
  rets!
  rgeo (= 0.4.0)
  rgeo-geojson (= 0.3.1)
  rgeo-shapefile (= 0.2.3)
  rubocop (= 0.32.1)
  sass-rails (= 5.0.4)
  selenium-webdriver (= 2.47.1)
  sidekiq (= 3.5.3)
  sidekiq-middleware (= 0.3.0)
  sidekiq-rate-limiter (= 0.1.0)
  simple_xlsx_reader (= 1.0.2)
  simplecov (= 0.9.2)
  sinatra (= 1.4.6)
  sitemap_generator (= 5.1.0)
  spliner (= 1.0.6)
  spring (= 1.5.0)
  sprockets-coffee-react (= 3.4.0)
  thin (= 1.6.4)
  timecop (= 0.8.0)
  twitter (= 5.15.0)
  tzip (= 0.0.4)
  uuidtools (= 2.1.5)
  web-console (= 2.2.1)
  webmock (= 1.22.3)
  whenever (= 0.9.4)
  yui-compressor (= 0.12.0)

BUNDLED WITH
   1.10.6
```

**Comment by panterch** [comment]
Getting the same error after running a bundle update with

<pre>
bundle list | grep sprockets
  * sprockets (3.5.2)
  * sprockets-coffee-react (3.4.0)
  * sprockets-rails (3.0.0)
</pre>

**Comment by jsdf** [comment]
I've just published 3.4.1, give it a try.

**Comment by panterch** [comment]
Fixed for me - thanks a lot!

:+1:

**Comment by psugihara** [comment]
:+1: fixed for us too.

thank you @jsdf!

**Comment by psugihara** [comment]
:sushi:
